spring:
  application:
    name: asset-management
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/asset_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: null
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: asset-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  
  # Configuration Properties
  configuration:
    processor:
      enabled: true

# JWT Configuration
jwt:
  secret: 46N/1J3y0uxfj7qg8IWxPGODzILeGQE8/2QlN7vMjtQWKKK9NwWLINm6F65EfQ5y7Sj+u1VPSRTj8qvtCZjinqdxmYLnkK6nn5Di0OvQ4Y2S2WhF1+m6A2sACpDH90MfH3euucXl2pBWIQFSIrRgshIYcedRvNwFmFze+UNsiW8ehMKheB4B8ERIfYCC0yY/yGgL2wXEEQZ/3v8g+2emfc6H2a6lvHj8w0v7wxs/7CgE6iyFafYPl+cVgmelF802Lemjka8teqF8SwqUFK76NDfHZV5rjUxyvZrms+kMmkOJGB61srGya2NazQMlXc+YDOoDX1O+xgsCcpZUxJ+OA==
  expiration: 86400000

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    com.example.asset_management: DEBUG
    org.springframework.kafka: INFO
    org.springframework.security: DEBUG

# System Configuration
app:
  loan:
    approval-threshold-days: 7
    due-reminder-days: 2
  notification:
    max-retry-attempts: 3
    retry-delay-seconds: 60

---
# Docker Profile Configuration
spring:
  config:
    activate:
      on-profile: docker
  
  # Database Configuration for Docker
  datasource:
    url: jdbc:mysql://mysql:3306/asset_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  
  # Disable Kafka for Docker POC
  kafka:
    bootstrap-servers: ""
    consumer:
      group-id: ""
      auto-offset-reset: ""
      key-deserializer: ""
      value-deserializer: ""
    producer:
      key-serializer: ""
      value-serializer: ""
  
  # Disable Kafka auto-configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# Logging Configuration for Docker
logging:
  level:
    com.example.asset_management: INFO
    org.springframework.kafka: OFF
    org.springframework.security: INFO
